# Generated by Django 5.0.6 on 2024-06-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transfer_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
