# Generated by Django 5.0.6 on 2024-06-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_cliente_reserva_cliente_rut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='destino',
        ),
        migrations.AddField(
            model_name='reserva',
            name='comuna',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='zona',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='comuna',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='zona',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
